import { supabase } from '../config/supabaseClient';
import { mapApiTokenRow, mapWebhookDeliveryRow, mapWebhookRow } from '../helpers/mappers';
import type { ApiToken, ApiTokenScope, CreatedApiToken, CreatedWebhook, Webhook, WebhookDelivery, WebhookEvent } from '../types/domain';

export const integrationRepository = {
  async listTokens(projectId: string): Promise<ApiToken[]> { const { data, error } = await supabase.from('api_tokens').select('id, project_id, name, token_prefix, scopes, revoked_at, created_at, updated_at').eq('project_id', projectId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []).map(mapApiTokenRow); },
  async createToken(projectId: string, name: string, scopes: ApiTokenScope[]): Promise<CreatedApiToken> { const { data, error } = await supabase.rpc('create_api_token', { p_project_id: projectId, p_name: name, p_scopes: scopes }); if (error) throw error; const row = data as any; return { ...mapApiTokenRow({ ...row, project_id: projectId, revoked_at: null, updated_at: row.created_at }), token: row.token }; },
  async revokeToken(id: string): Promise<void> { const { error } = await supabase.rpc('revoke_api_token', { p_token_id: id }); if (error) throw error; },
  async listWebhooks(projectId: string): Promise<Webhook[]> { const { data, error } = await supabase.from('webhooks').select('id, project_id, name, url, events, is_active, max_retries, created_at, updated_at').eq('project_id', projectId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []).map(mapWebhookRow); },
  async createWebhook(projectId: string, input: { name: string; url: string; events: WebhookEvent[]; maxRetries: number }): Promise<CreatedWebhook> { const { data, error } = await supabase.rpc('create_webhook', { p_project_id: projectId, p_name: input.name, p_url: input.url, p_events: input.events, p_max_retries: input.maxRetries }); if (error) throw error; const row = data as any; return { ...mapWebhookRow({ ...row, project_id: projectId, updated_at: row.created_at }), secret: row.secret }; },
  async updateWebhook(id: string, changes: { isActive?: boolean; maxRetries?: number }): Promise<Webhook> { const payload: Record<string, unknown> = {}; if (changes.isActive !== undefined) payload.is_active = changes.isActive; if (changes.maxRetries !== undefined) payload.max_retries = changes.maxRetries; const { data, error } = await supabase.from('webhooks').update(payload).eq('id', id).select('id, project_id, name, url, events, is_active, max_retries, created_at, updated_at').single(); if (error) throw error; return mapWebhookRow(data); },
  async rotateWebhookSecret(id: string): Promise<string> { const { data, error } = await supabase.rpc('rotate_webhook_secret', { p_webhook_id: id }); if (error) throw error; return (data as any).secret as string; },
  async listDeliveries(projectId: string): Promise<WebhookDelivery[]> { const { data, error } = await supabase.from('webhook_deliveries').select('id, webhook_id, project_id, event, resource_id, status, attempt_count, next_attempt_at, response_status, delivered_at, last_error, created_at').eq('project_id', projectId).order('created_at', { ascending: false }).limit(100); if (error) throw error; return (data ?? []).map(mapWebhookDeliveryRow); },
};
